### ISSUE TITLE
Error when calling: mq.Get(queueHandle,md,gmo,getCB)

### ISSUE THREAD

**Issue by mortenLom** [ibm-messaging/mq-mqi-nodejs#17] opened 2017-12-05 08:44 UTC
Hi
I have made a .js file based on the sample files amqsput.js and amqsgeta.js. When I run this file alone, everything works fine.
Then I integrate this file into a webapplication made from swagger. I make my main function visible to the other files. I.e. I modify my main function from
function putgetmq() { to
exports.putgetmq = function() {
When I now run the application, the line
mq.Get(queueHandle,md,gmo,getCB);
fails. I get the following error:

/home/morten/workspace/nodejs-server-server-generated/nodejs-server-server/node_modules/ffi/lib/callback.js:20
        throw err
        ^
MQError: MQCallback: MQCC = MQCC_FAILED [2] MQRC = MQRC_HCONN_ERROR [2018]
    at mqiCB (/home/morten/workspace/nodejs-server-server-generated/nodejs-server-server/node_modules/ibmmq/lib/mqi.js:1153:11)
    at /home/morten/workspace/nodejs-server-server-generated/nodejs-server-server/node_modules/ffi/lib/callback.js:66:25
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! notes@0.0.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the notes@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/morten/.npm/_logs/2017-12-05T07_57_12_367Z-debug.log

Any idea what this is? Thanks for any help.
Morten

**Comment by ibmmqmet** [comment] 2017-12-05 10:59
Is it possible that your callback function (getCB) is throwing an exception? That might be being caught and then the MQ code is throwing a default error. 
Otherwise, I suspect an MQ trace of the application might be needed to see if there really is an HCONN_ERROR coming back from an MQ function.

**Comment by mortenLom** [comment] 2017-12-05 14:04
Thanks for the answer. 
I would like to add: Occasionally (maybe 1 out of 10?), the error does not show up. 

Another thing. I copied the line: cleanup(connectionHandle,queueHandle); into getCB. Then I got the error:
MQ call failed in CLOSE: MQCC = MQCC_FAILED [2] MQRC = MQRC_HCONN_ASYNC_ACTIVE [2500]. Does that mean that I cannot close and disconnect from within the callback function?

Morten

**Comment by mortenLom** [comment] 2017-12-11 07:36
I am still struggling with this. The funny thing is that when I run the .js file alone (node putget.js) everything works fine. However, when I call an exported function in the same putget.js file from another .js file it fails (npm start). Could it be that I "lose" some of the variables by the fact that I am calling the function from another file? I.e. that there is something that I have not understood about node.js when it comes to multiple .js files?
Another questions. You mention, MQ trace. I might have to do that. How do I do an MQ trace?
Thanks.
Morten

**Comment by mortenLom** [comment] 2017-12-11 21:36
I did some more testing just now. I am now able to call my putget() routine from another .js file with callback and all. It worked fine. So the problem is not that I have two .js files. The error comes when I integrate with swagger and express. I use swagger to generate a stub file. Then I fill in code in the stub functions. Its from one of these functions that I call my putget() function. When I run this, the error comes. So I have like this:
DefaultServices.js: (swagger functions)
exports.getNotesById = function(args, res, next) {
  mymq.putget( function(err,hObj,gmo,md,buf) {
      .. the callback from mq.Get should end up here
  }
putget.js:
exports.putget = function (cb) {
   mq.Connx(...    (put from sample)
   mq.Conn( ... (get from sample))
}
Does the fact that I use swagger and express, cause the error in mqi.js?
Morten

**Comment by mortenLom** [comment] 2017-12-12 07:26
To sum up:
1. The error does not occur when I run my putget.js file standalone (i.e. node putget.js). The file is based on the sample programs: amqsput.js and amqsgeta.js
2. The error does not occur when I export my putget() function inside the putget.js and call it from another .js file.
3. The error occurs when I integrate with swagger and express, i.e. when I call the putget() function from the 'swagger' function getNotesById(). The error happens sometime after mq.Get(queueHandle,md,gmo,getCB) is called. GetCB is never called. 
4. The error comes maybe 9 times out of 1. I.e. sometimes it works. 
I really need some help now. Could there we a bug in the ibmmq code?
Thanks.
Morten

**Comment by ibmmqmet** [comment] 2017-12-12 09:03
I wouldn't claim to write perfect code, so there's always a possibility of a bug in the ibmmq module. But I can't see what it might be at the moment. 

As I said before, an HCONN_ERROR suggests something around the process threading not behaving as expected. An MQ trace might show if the error is coming from within the real MQ library or this JS wrapper. The update I pushed to the repo yesterday contains various enhancements, including a script that shows how to do an MQ trace - see "tests/mqset". 

But you may end up needing to do some debugging yourself (eg inserting console output in the mqi.js file), to check what's going on in and under mq.Get() as I don't have your actual programs or environment to test with. For example, to see if the internal mqiCB function is being called when the message appears.

**Comment by mortenLom** [comment] 2017-12-15 09:24
Thanks. I include MQ trace for:
1. Successful run of the putget.js file standalone (i.e. node putget.js). In this run the callback function getCB is called as it should
2. Unsuccessful run of the same code, but this time run with the complete application (including the web server, express, and swagger). This time the callback function getCB is not called because of the error (at the top). Could you have a quick look at the traces? Do you see anything that could explain the it?
Thanks. Morten

[trace-OK-local.tar.gz](https://github.com/ibm-messaging/mq-mqi-nodejs/files/1562127/trace-OK-local.tar.gz)
[trace-NOK-full.tar.gz](https://github.com/ibm-messaging/mq-mqi-nodejs/files/1562128/trace-NOK-full.tar.gz)

**Comment by ibmmqmet** [comment] 2017-12-15 14:30
The failing trace shows no problem in the MQ C code. The last thing that happens looks to be the callback to the JS layer. And any exception is coming from within that or from your callback nested within it. So it's going to be a case of debugging what's happening in the mqiCB function in mqi.js. I'd suggest you insert some printing in that method to see how far it gets through as I can't replicate your environment or problem. The exception that you are getting will show the line number in the mqiCB function to give an idea of the flow - which is fairly simple. (And make sure you really are running with the latest level of this package.)

**Comment by mortenLom** [comment] 2017-12-18 10:54
Thanks for your help. I will try this and let you know how it goes :-)

**Comment by mortenLom** [comment] 2017-12-19 14:22
Hi
Now I have added some printing in the mqiCB() function in mqi.js file. The first place where things go wrong, is when jsObject is given a value, i.e. at these code lines:
  ...
  var jsObject = null;
  try {
    jsObject = p?JSON.parse(ref.readCString(p)):null;
    console.log('mqiCB: jsObject = ', jsObject);
  } catch (err) {
    console.log('mqiCB: Error1');
  }
  console.log('mqiCB: jsObject2 = ', jsObject);
..
When it fails, the catch (err) is triggered and jsObject gets the value = null. 
The console output is shown below:
..
mqiCB: start
mqiCB: mqcbc =  { StrucId: [ 67, 66, 67, 32, buffer: <Buffer@0x250bb30 43 42 43 20> ],
  Version: 2,
  CallType: 6,
  Hobj: 101,
  CallbackArea: <Buffer@0x247df10 >,
  ConnectionArea: <Buffer@0x(nil) >,
  CompCode: 0,
  Reason: 0,
  State: 0,
  DataLength: 429,
  BufferLength: 429,
  Flags: 0,
  ReconnectDelay: 0,
  'ref.buffer': <Buffer@0x250bb30 43 42 43 20 02 00 00 00 06 00 00 00 65 00 00 00 10 df 47 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ad 01 00 00 ad 01 ... > }
mqiCB: Error1
mqiCB: jsObject2 =  null

/home/morten/workspace/nodejs-server-server-generated/nodejs-server-server/node_modules/ffi/lib/callback.js:20
        throw err
        ^
MQError: MQCallback: MQCC = MQCC_FAILED [2] MQRC = MQRC_HCONN_ERROR [2018] [Pkg ver = 0.2.2]
    at mqiCB (/home/morten/workspace/nodejs-server-server-generated/nodejs-server-server/node_modules/ibmmq/lib/mqi.js:1364:11)
    at /home/morten/workspace/nodejs-server-server-generated/nodejs-server-server/node_modules/ffi/lib/callback.js:66:25
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! notes@0.0.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the notes@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/morten/.npm/_logs/2017-12-19T13_52_25_302Z-debug.log

When I run locally (node putget.js) jsObject gets this value:
mqiCB: jsObject =  { _hObj: 101,
  _mqQueueManager: { _hConn: 16777223, _name: 'M06T' },

Does this tell you something? Thanks for any help.
Morten
  _name: 'QA.TEST07.FHS_NITRA_RESOURCE_REP' }

**Comment by ibmmqmet** [comment] 2017-12-19 17:39
Thanks for trying that. I've got an idea, though I can't prove it. I'm suspecting that garbage collection may be kicking in when I don't want it to. I'm attaching a modified mqi.js file which tries to keep a variable out of GC's scope, and also logs a couple of possible error conditions. To use this file, you'll need to update to today's level of code first. 

[mqi.js.zip](https://github.com/ibm-messaging/mq-mqi-nodejs/files/1572628/mqi.js.zip)

**Comment by ravellan** [comment] 2017-12-19 23:40
I believe I ran into the same issue while testing async get. I was running a slightly modified amqsgeta (just adding a client binding connection) and when starting with 5 or more messages on the queue it would crash every time after 3-4 messages retrieved. I also narrowed it down to `ref.readCString(p)` returning a garbage string.

Now with your attached version the issue is gone verified with 1k messages on queue with clean exit.

**Comment by mortenLom** [comment] 2017-12-20 07:32
Thanks. I have updated to 0.3.0 and tested with your added mqi.js file. My initial findings are: It works sometimes. but not always. When it fails I get:

Cannot parse callbackArea "���\u0003"

/home/morten/workspace/nodejs-server-server-generated/nodejs-server-server/node_modules/ffi/lib/callback.js:20
        throw err
        ^
MQError: MQCallback: MQCC = MQCC_FAILED [2] MQRC = MQRC_HCONN_ERROR [2018] [Pkg ver = 0.3.0]
    at mqiCB (/home/morten/workspace/nodejs-server-server-generated/nodejs-server-server/node_modules/ibmmq/lib/mqi.js:1444:11)
    at /home/morten/workspace/nodejs-server-server-generated/nodejs-server-server/node_modules/ffi/lib/callback.js:66:25
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! notes@0.0.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the notes@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Morten

**Comment by ibmmqmet** [comment] 2018-01-02 15:19
I have never been able to duplicate this particular error.

However, while doing increasingly more complex tests in order to see what might be happening, I found a very nasty deadlock in the way that the Node and MQ threading models could interfere with each other. So I've just pushed a new version of the package that completely rewrites the async get so this particular problem should not occur.

The new async Get() has to emulate asynchronous operations by doing a polling MQGET. Not ideal but it does seem to work - the poll interval is configurable, default 1 second. There should be no changes to application code required as a result of this redesign, but you ought now to be able to call GetDone() from within the async message consumer, instead of having to run it separately via setInterval().

**Comment by mortenLom** [comment] 2018-01-04 07:51
Thanks. Now it seems to work. I will take a closer look.

Just a minor thing. When I upgraded, I got 0.3.6, not 0.3.5:
[morten@localhost nodejs-server-server]$ sudo npm update ibmmq
+ ibmmq@0.3.6
removed 1 package and updated 1 package in 3.559s

[morten@localhost nodejs-server-server]$ npm list | grep ibmmq
├─┬ ibmmq@0.3.6

**Comment by ibmmqmet** [comment] 2018-01-04 11:33
.3.6 was a minor update that I didn't bother putting in the README. But I've now just pushed .3.7 which has a couple of fixes to how the waitInterval works.

**Comment by ibmmqmet** [comment] 2018-01-08 19:29
Since this particular problem cannot now occur with the new design, I'm going to close it. Other problems found in the Get() processing should be in a new issue.

**Closed by ibmmqmet** 2018-01-08 19:29 UTC
