### ISSUE TITLE
Unable to get client to work with latest versions of Debian and Node

### ISSUE THREAD

**Issue by creasman** [ibm-messaging/mq-mqi-nodejs#85] opened 2020-05-19 16:30 UTC
I'm creating a base Docker container to use as a starting point for other Node-based services that will use the Node MQ client.  We are trying to make the container as light weight as possible and prefer to use one of the Debian slim versions.  I began by following the sample Docker file here that uses Debian (Jessie-slim) with Node 8 and that worked.  

I then tried moving up to Debian (Buster-slim) and Node 14.  In this case there are OS exceptions  whenever the MQ client loads.  I am pulling from the master branch of mq-mqi-nodejs.

What I currently have working is Debian (Stretch-slim) with Node 12.16.3.  Rather than installing all these directly as the sample Dockerfile does, I switched to using the official Node images from Docker hub, here:  https://hub.docker.com/_/node/ as the base -- mainly for simplicity.  This is how my Dockerfile begins:

     FROM node:12.16.3-stretch-slim 

Anything more recent than that does not work for me.  It fails as soon as the container comes up and attempts to connect.  

The exception text references NAPI.  Since "stretch" is a fairly recent version of Debian, and the code works with Node 12, I suspect there is some sort of problem between the MQ client binaries and those pulled in by later versions of Node.  Has anyone else reported a similar issue?  Is there a support statement or test matrix I can reference to know the best choice of Linux/Node container to use?

Thanks,
Jim

**Comment by ibmmqmet** [comment] 2020-05-21 09:50
I was able to use both stretch and buster with Node 12 using the sample Dockerfile and a version of package.json that references a recent version of the ibmmq library. 

There seems to be a known issue with the node-ffi-napi component with Node 14 that might have been fixed in the last few days, caused by redesigns in the node engine. See https://github.com/node-ffi-napi/ref-napi/issues/25

**Comment by creasman** [comment] 2020-05-21 19:52
Thanks for the update.  I will give this another try.

**Closed** 2020-06-19 17:32 UTC
